### ISSUE TITLE
callPeak question

### ISSUE THREAD

**Issue by CCCBBG** [StatBiomed/scTail#1]
scTail-callPeak -b $bamFile --gtf $gtfFile --cellbarcode $cellbarcodeFile -f $fastaFile --species human --chromoSize $chromosomeSize -o $outputfile --minCount 50 -p 20

[*] Selected device:  cpu
Traceback (most recent call last):
  File "/home01/chenbg/miniconda3/envs/run_scTail/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'cellbarcode'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home01/chenbg/miniconda3/envs/run_scTail/bin/scTail-callPeak", line 8, in <module>
    sys.exit(main())
  File "/home01/chenbg/miniconda3/envs/run_scTail/lib/python3.9/site-packages/scTail/bin/callPeak.py", line 142, in main
    getPAScluster=GetPAScluster(PASrefpath,generefpath,fasta_file,bam_file,out_dir,n_proc,minCount,maxReadCount,densityFC,InnerDistance,device,chromoSizePath,cellbarcodePath,species)
  File "/home01/chenbg/miniconda3/envs/run_scTail/lib/python3.9/site-packages/scTail/utils/getPAS.py", line 31, in __init__
    self.cellbarcode=pd.read_csv(cellbarcodePath,delimiter='\t')['cellbarcode'].values
  File "/home01/chenbg/miniconda3/envs/run_scTail/lib/python3.9/site-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home01/chenbg/miniconda3/envs/run_scTail/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'cellbarcode'

but I check the barcode.tsv
head -n 5 $cellbarcodeFile
AAACCCAATGAAACACT
AAACCCAATGAAACCAT
AAACCCAATGAAACCCA
AAACCCAATGAAACCCG
AAACCCAATGAAATGAG

what's the matter with my code?
I am looking forward to your reply

**Comment by houruiyan** [comment]
Hi,

Thank you very much for your question. I guess that is because you did not add the column name in your barcode file. Could you add the "cellbarcode" as the column name of your barcode file, just looking like the example file in our figshare. 

Best regards,
Ruiyan

**Comment by CCCBBG** [comment]
Oh，thanks very much !!!
